version: '3.8'
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx_config:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - profkom_server_net

  app:
    build: ./app
    restart: always
    depends_on:
      - mongodb
    networks:
      - profkom_server_net

  mongodb:
    image: mongo
    restart: always
    volumes:
      - data:/data/db
    networks:
      - profkom_server_net

volumes:
  data:
networks:
  profkom_server_net:
    name: profkom_server_net