version: '3.3'
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx_config:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - profkom_server_net

  app:
    build: ./app
    restart: always
    env_file: .env
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - mongodb
    networks:
      - profkom_server_net

  mongodb:
    image: mongo
    restart: always
    volumes:
      - data:/data/db
    networks:
      - profkom_server_net

volumes:
  data:
networks:
  profkom_server_net: