version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ./nginx_config:/etc/nginx/conf.d:z
    depends_on:
      - app

  app:
    build: ./app
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db

volumes:
  data:
