version: '3.3'
services:
  app:
    build: ./app
    env_file: .env
    command: "pytest -vv"
    volumes:
      - ./app:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always

