version: '3.3'
services:
  bot:
    build: .
    restart: always
    depends_on:
      - redis
    networks:
      - profkom_bot_net

  redis:
    image: redis
    restart: always
    networks:
      - profkom_bot_net

networks:
  profkom_bot_net:
    external:
      name: server_profkom_server_net
