#version: '3'
#services:
#  bot:
#    build: .
#    restart: always
#    depends_on:
#      - redis
#    networks:
#      - bot_sec_network
#    command: python3 bot_run.py
#
#  redis:
#    image: redis
#    restart: always
#    networks:
#      - bot_sec_network
#
#networks:
#  bot_sec_network:
#    external:
#      name: bot_network
